In [1]:
import pandas as pd
df=pd.read_csv("bike_buyers_clean.csv")
df.head()

ID Marital Status  Gender  Income  Children        Education  \
0  12496        Married  Female   40000         1        Bachelors   
1  24107        Married    Male   30000         3  Partial College   
2  14177        Married    Male   80000         5  Partial College   
3  24381         Single    Male   70000         0        Bachelors   
4  25597         Single    Male   30000         0        Bachelors   

       Occupation Home Owner  Cars Commute Distance   Region  Age  \
0  Skilled Manual        Yes     0        0-1 Miles   Europe   42   
1        Clerical        Yes     1        0-1 Miles   Europe   43   
2    Professional         No     2        2-5 Miles   Europe   60   
3    Professional        Yes     1       5-10 Miles  Pacific   41   
4        Clerical         No     0        0-1 Miles   Europe   36   

  Purchased Bike  
0             No  
1             No  
2             No  
3            Yes  
4            Yes

In [2]:
df.isnull().sum()

ID                  0
Marital Status      0
Gender              0
Income              0
Children            0
Education           0
Occupation          0
Home Owner          0
Cars                0
Commute Distance    0
Region              0
Age                 0
Purchased Bike      0
dtype: int64

In [3]:
df=df.drop(["ID","Gender"],axis=1)
df.head()

Marital Status  Income  Children        Education      Occupation  \
0        Married   40000         1        Bachelors  Skilled Manual   
1        Married   30000         3  Partial College        Clerical   
2        Married   80000         5  Partial College    Professional   
3         Single   70000         0        Bachelors    Professional   
4         Single   30000         0        Bachelors        Clerical   

  Home Owner  Cars Commute Distance   Region  Age Purchased Bike  
0        Yes     0        0-1 Miles   Europe   42             No  
1        Yes     1        0-1 Miles   Europe   43             No  
2         No     2        2-5 Miles   Europe   60             No  
3        Yes     1       5-10 Miles  Pacific   41            Yes  
4         No     0        0-1 Miles   Europe   36            Yes

In [5]:
df.dtypes

Marital Status      object
Income               int64
Children             int64
Education           object
Occupation          object
Home Owner          object
Cars                 int64
Commute Distance    object
Region              object
Age                  int64
Purchased Bike      object
dtype: object

In [6]:
df["Income"]=df["Income"].astype("float")
df.dtypes

Marital Status       object
Income              float64
Children              int64
Education            object
Occupation           object
Home Owner           object
Cars                  int64
Commute Distance     object
Region               object
Age                   int64
Purchased Bike       object
dtype: object

In [8]:
cclum=[]
for i in df.columns:
    if df[i].dtypes=="object":
        cclum.append(i)
print(cclum)
from sklearn import preprocessing
le = preprocessing.LabelEncoder()   
df[cclum]=df[cclum].apply(le.fit_transform)
df.head()

['Marital Status', 'Education', 'Occupation', 'Home Owner', 'Commute Distance', 'Region', 'Purchased Bike']


Marital Status   Income  Children  Education  Occupation  Home Owner  Cars  \
0               0  40000.0         1          0           4           1     0   
1               0  30000.0         3          3           0           1     1   
2               0  80000.0         5          3           3           0     2   
3               1  70000.0         0          0           3           1     1   
4               1  30000.0         0          0           0           0     0   

   Commute Distance  Region  Age  Purchased Bike  
0                 0       0   42               0  
1                 0       0   43               0  
2                 3       0   60               0  
3                 4       2   41               1  
4                 0       0   36               1

In [8]:
cclum=[]
for i in df.columns:
    if df[i].dtypes=="object":
        cclum.append(i)
print(cclum)
from sklearn import preprocessing
le = preprocessing.LabelEncoder()   
df[cclum]=df[cclum].apply(le.fit_transform)
df.head()cclum=[]
for i in df.columns:
    if df[i].dtypes=="object":
        cclum.append(i)
print(cclum)
from sklearn import preprocessing
le = preprocessing.LabelEncoder()   
df[cclum]=df[cclum].apply(le.fit_transform)
df.head()

['Marital Status', 'Education', 'Occupation', 'Home Owner', 'Commute Distance', 'Region', 'Purchased Bike']


Marital Status   Income  Children  Education  Occupation  Home Owner  Cars  \
0               0  40000.0         1          0           4           1     0   
1               0  30000.0         3          3           0           1     1   
2               0  80000.0         5          3           3           0     2   
3               1  70000.0         0          0           3           1     1   
4               1  30000.0         0          0           0           0     0   

   Commute Distance  Region  Age  Purchased Bike  
0                 0       0   42               0  
1                 0       0   43               0  
2                 3       0   60               0  
3                 4       2   41               1  
4                 0       0   36               1

In [9]:
x=df.drop(["Purchased Bike"],axis=1)
y=df["Purchased Bike"]
x=x.to_numpy()
x.shape

(1000, 10)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(800, 10) (200, 10) (800,) (200,)


In [17]:
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import confusion_matrix,classification_report
names=["SVM","NB","KNN","DT","RF","ET"]
clfs=[SVC(),GaussianNB(),KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier(),ExtraTreesClassifier()]
CLFF=[]
for name,clf in zip(names,clfs):
    print(name)
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    CLFF.append(clf)
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print('-----------------------------------------------')

SVM
[[24 82]
 [29 65]]
              precision    recall  f1-score   support

           0       0.45      0.23      0.30       106
           1       0.44      0.69      0.54        94

    accuracy                           0.45       200
   macro avg       0.45      0.46      0.42       200
weighted avg       0.45      0.45      0.41       200

-----------------------------------------------
NB
[[64 42]
 [47 47]]
              precision    recall  f1-score   support

           0       0.58      0.60      0.59       106
           1       0.53      0.50      0.51        94

    accuracy                           0.56       200
   macro avg       0.55      0.55      0.55       200
weighted avg       0.55      0.56      0.55       200

-----------------------------------------------
KNN
[[79 27]
 [31 63]]
              precision    recall  f1-score   support

           0       0.72      0.75      0.73       106
           1       0.70      0.67      0.68        94

    accuracy      

In [18]:
import pickle
pickle.dump(CLFF,open("model_bike.pkl","wb"))