In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
#df=df.drop(["Columnname"],axis=1)  #drop Colum
#df=df.dropna() #drop null rows

In [5]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [6]:
x=df.drop(["species"],axis=1)
y=df["species"]
x=x.to_numpy()
x.shape

(150, 4)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.50, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(75, 4) (75, 4) (75,) (75,)


In [9]:
from sklearn.svm import SVC
clf=SVC()
clf.fit(X_train,y_train)

SVC()

In [10]:
y_pred=clf.predict(X_test)
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa',
       'setosa', 'setosa', 'versicolor', 'virginica', 'setosa', 'setosa',
       'setosa', 'versicolor', 'setosa', 'versicolor', 'virginica',
       'setosa', 'versicolor', 'virginica', 'setosa', 'virginica',
       'virginica'

In [11]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        29
  versicolor       1.00      1.00      1.00        23
   virginica       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75



In [12]:
clf.predict([[1.2,1.3,4.1,1.5]])

array(['virginica'], dtype=object)

In [13]:
import pickle
pickle.dump(clf,open("model_iris.pkl","wb"))